
export const SIdebarData = [
    {
        title:"Dashboard",
        list:[
            {
                title:"Users",
                path:"/dashboard/users",
                icon:""
            },
            {
                title:"Annual Income",
                path:"/dashboard/anualincome",
                icon:""
            },
            {
                title:"Weekly Income",
                path:"/dashboard/weeklyincome",
                icon:""
            }
        ]
    },
    {
        title:"Statics",
        list:[
            {
                title:"Graph",
                path:"/dashboard/graph",
                icon:""
            },
            {
                title:"Feed",
                path:"/dashboard/feed",
                icon:""
            },
            {
                title:"Like",
                path:"/dashboard/like",
                icon:""
            },
        ]
    },
    {
        title:"Wallet",
        list:[
            {
                title:"Money Amount",
                path:"/dashboard/monyAmount",
                icon:""
            },
            {
                title:"Bank",
                path:"/dashboard/bank",
                icon:""
            },
        ]
    },
    {
        title:"Message",
        list:[
            {
                title:"Sms System"
            }
        ]
    },
    {
        title:"Profile",
        list:[
            {
                title:"Bio-data"
            }
        ]
    },
    {
        title:"Favorite",
        list:[
            {
                title:"Sports"
            }
        ]
    },
    {
        title:"Transfers",
        list:[
            {
                title:"Usd"
            }
        ]
    }
]
